ports:
  - port: 3000
    onOpen: open-browser

tasks:
  - name: Dev Server
    init: |
      cd chickomat
      npm ci
    command: |
      cd chickomat
      npm run dev

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false